export { default as Welcome } from "@/components/pages/Welcome";
export { default as CreateWallet } from "@/components/pages/CreateWallet";
export { default as Dashboard } from "@/components/pages/Dashboard";
export { default as Receive } from "@/components/pages/Receive";
export { default as Send } from "@/components/pages/Send";
export { default as ImportWallet } from "@/components/pages/ImportWallet";
export { default as Buy } from "@/components/pages/Buy";
export { default as NotFoundPage } from "@/components/pages/NotFoundPage";
export { default as Profile } from "@/components/pages/Profile"